FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview
WORKDIR /app
EXPOSE 8080
RUN apt-get update && apt-get install -y unzip curl python3 python3-pip && \
    pip3 install botocore boto3 --break-system-packages && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip -q awscliv2.zip && ./aws/install && rm -rf awscliv2.zip aws && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
