using LegalManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LegalManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603210000_AddMissingPublicacaoColumns")]
    public partial class AddMissingPublicacaoColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // These columns were in the EF model snapshot but never generated by any Up() migration.
            // Using IF NOT EXISTS so this is safe on both fresh databases and existing ones.
            migrationBuilder.Sql(@"
                ALTER TABLE ""Publicacoes""
                    ADD COLUMN IF NOT EXISTS ""HashDje"" text,
                    ADD COLUMN IF NOT EXISTS ""IdExterno"" text,
                    ADD COLUMN IF NOT EXISTS ""OrigemId"" bigint,
                    ADD COLUMN IF NOT EXISTS ""Pagina"" text,
                    ADD COLUMN IF NOT EXISTS ""Secao"" text;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(name: "HashDje", table: "Publicacoes");
            migrationBuilder.DropColumn(name: "IdExterno", table: "Publicacoes");
            migrationBuilder.DropColumn(name: "OrigemId", table: "Publicacoes");
            migrationBuilder.DropColumn(name: "Pagina", table: "Publicacoes");
            migrationBuilder.DropColumn(name: "Secao", table: "Publicacoes");
        }
    }
}
